site:
  title: Climatology Plugin Manual
  url:  https://nowhere.net
  start_page: climatology:ROOT:climatology.adoc

content:
  sources:
    - url: ../..
      start_path: manual/climatology
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/climatology_pi/edit/master/{path}

ui:   
  bundle:
    url: https://gitlab.com/leamas/antora-ui-default/-/raw/master/latest/ui-bundle.zip
    snapshot: true

output:
  dir: ./docs
  clean: true              
